"""empty message

Revision ID: a5a29c2677b7
Revises: d4bb2a30bdac
Create Date: 2024-12-02 18:13:50.966684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a29c2677b7'
down_revision = 'd4bb2a30bdac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))

    op.drop_table('likes')
    # ### end Alembic commands ###
